### ISSUE TITLE
Output from NTLMRawUnhide not cracked by hashcat because of backslash in user name field.

### ISSUE THREAD

**Issue by vegardw** [mlgualtieri/NTLMRawUnHide#2]
For testing NTLMRawUnhide I captured a NTLMv2 challenge in my AD lab for a user I had created with a password from rockyou.txt

The password was cracked without problems by John the Ripper, but hashcat 6.1.1 wouldn't crack it.

After some testing testing I found that the backslash in the username field was the problem.

Changing it from `ADLAB\dabob::DC01:30d31bd5(...)` to `dabob::ADLAB:30d31bd5(...)` or `dabob::DC01:30d31bd5(...)`  made hashcat crack the hash without problems.  

Looking at the hashcat example hashes at https://hashcat.net/wiki/doku.php?id=example_hashes, the username field there contains only the username, not the domain.

## Attached
The attached file, [files.zip](https://github.com/mlgualtieri/NTLMRawUnHide/files/6260105/files.zip) contains the following:
- trace.etl: the capture I ran NTLMRawUnhide on
- hashes.txt: The file output by NTLMRawUnhide, which JtR did crack, but not hashcat
-  hashes_modified.txt: The modified file that were cracked by both JtR and hashcat

**Comment by mlgualtieri** [comment]
Just pushed out an update.  See if the latest fixes the issue.  Based on what you describe it should work for both hashcat and john now.

With the change, if a domain is found, it outputs this in the workstation field - otherwise the workstation is essentially the domain, so it outputs the workstation instead.  The username no longer outputs Domain\Username since that appears to break hashcat.

**Comment by vegardw** [comment]
Yes, that fixed the issue. Both JtR and hashcat cracked it now. Thanks!
